<?php

/**
 * @package     Yepr Gen Library
 * @subpackage  Output
 *
 * @license     GNU General Public License version 3 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace Yepr\Gen\Core\Output;

/**
 * Carries hand-written code across a regeneration.
 *
 * Generated files mark editable areas:
 *
 *     // <gen id="index.custom">
 *     $item->addTaxonomy('Cuisine', $item->cuisine);
 *     // </gen>
 *
 * When a file is regenerated, the regions of the previous version are lifted out
 * by id and put back into the new one. Regions the new template no longer has are
 * reported rather than dropped quietly, because losing someone's code without
 * telling them is the worst thing a generator can do.
 *
 * The marker tag is configurable because each consuming project stamps its own
 * name into the files it generates, and a file generated by one tool should not
 * carry another tool's marker.
 *
 * @since  0.2.0
 */
final class ProtectedRegionMerger
{
    /**
     * The tag used in the region markers.
     *
     * @var    string
     * @since  0.2.0
     */
    private string $tag;

    /**
     * The compiled pattern matching one region.
     *
     * @var    string
     * @since  0.2.0
     */
    private string $pattern;

    /**
     * Ids that existed in the old file but not in the new one.
     *
     * @var    string[]
     * @since  0.2.0
     */
    private array $orphans = [];

    /**
     * Constructor.
     *
     * @param   string  $tag  The marker tag, for example "extengen".
     *
     * @throws  \InvalidArgumentException  When the tag is not a usable element name.
     *
     * @since   0.2.0
     */
    public function __construct(string $tag = 'gen')
    {
        if (!preg_match('/^[A-Za-z][A-Za-z0-9_-]*$/', $tag)) {
            throw new \InvalidArgumentException(\sprintf('"%s" is not a usable region tag.', $tag));
        }

        $this->tag     = $tag;
        $this->pattern = '~^([ \t]*)(?://|#|\*|<!--)?\s*<' . preg_quote($tag, '~')
            . ' id="([A-Za-z0-9_.\-]+)">.*?\R(.*?)^[ \t]*(?://|#|\*|<!--)?\s*</'
            . preg_quote($tag, '~') . '>~ms';
    }

    /**
     * Put the previous version's hand-written regions into a freshly generated file.
     *
     * @param   string  $existing   The file as it is on disk now; may be empty.
     * @param   string  $generated  The freshly generated file.
     *
     * @return  string  The generated file with the kept regions merged back in.
     *
     * @since   0.2.0
     */
    public function merge(string $existing, string $generated): string
    {
        $this->orphans = [];

        if (trim($existing) === '') {
            return $generated;
        }

        $kept = $this->extract($existing);

        if ($kept === []) {
            return $generated;
        }

        $used   = [];
        $merged = preg_replace_callback(
            $this->pattern,
            static function (array $match) use ($kept, &$used): string {
                $id = $match[2];

                if (!isset($kept[$id])) {
                    return $match[0];
                }

                $used[$id] = true;

                // Keep the generated markers, swap only the body.
                $body  = rtrim($kept[$id], "\r\n");
                $open  = substr($match[0], 0, (int) strpos($match[0], "\n") + 1);
                $close = substr($match[0], (int) strrpos($match[0], "\n") + 1);

                return $open . ($body === '' ? '' : $body . "\n") . $close;
            },
            $generated
        );

        $this->orphans = array_values(array_diff(array_keys($kept), array_keys($used)));

        return $merged ?? $generated;
    }

    /**
     * Region ids that the previous file had and the new one does not.
     *
     * Their content was not carried over and is only in the file on disk, so a
     * caller must surface this rather than ignore it.
     *
     * @return  string[]  The orphaned ids from the last merge.
     *
     * @since   0.2.0
     */
    public function orphanedRegions(): array
    {
        return $this->orphans;
    }

    /**
     * Pull every non-empty region out of a file.
     *
     * @param   string  $source  The file contents.
     *
     * @return  array<string, string>  Region id => body.
     *
     * @since   0.2.0
     */
    public function extract(string $source): array
    {
        $regions = [];

        if (preg_match_all($this->pattern, $source, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $match) {
                $body = $match[3];

                if (trim($body) !== '') {
                    $regions[$match[2]] = $body;
                }
            }
        }

        return $regions;
    }

    /**
     * Render a region for a template to emit.
     *
     * @param   string   $id      The region id, unique within the file.
     * @param   string   $body    Generated default content, if any.
     * @param   integer  $levels  Indentation levels of four spaces.
     *
     * @return  string  The rendered region, without a trailing newline.
     *
     * @since   0.2.0
     */
    public function region(string $id, string $body = '', int $levels = 2): string
    {
        $pad  = str_repeat(' ', $levels * 4);
        $body = rtrim($body, "\r\n");

        return $pad . '// <' . $this->tag . ' id="' . $id . '">' . "\n"
            . ($body === '' ? '' : $body . "\n")
            . $pad . '// </' . $this->tag . '>';
    }
}
